### ISSUE TITLE
Project budget

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#10]
## Description

The overall financial cost or amount is a summary total financial sum for the activity.

This is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the default aid type code is administrative costs (G01).

## Proposed tests

Firstly:
```python
Budget available forward annually
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not G01
    And `activity-date[@type="3" or @type="4" or @type="end-planned" or @type="end-actual"]/@iso-date` is at least 6 months ahead
    Then `budget | planned-disbursement` should be available forward annually
 ```
 
Secondly:
```python
Budget available forward quarterly
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not G01
    And `activity-date[@type="3" or @type="4" or @type="end-planned" or @type="end-actual"]/@iso-date` is at least 6 months ahead
    Then `budget | planned-disbursement` should be available forward quarterly
 ```

**Comment by malclopez** [comment]
The tester is expecting annual budget and quarterly budget  for closed projects.  Perhaps, the test/condition should be revised to consider that when 'actual end date' exists (activity date type = 4), then budget should no longer be expected. There are cases when 'actual end date' occur ahead of the 'planned end date'.

**Comment by jzheng-79** [comment]
Quarterly data is simply not available as our budget planning is on an annual basis.

**Comment by publishwhatyoufund** [comment]
> The tester is expecting annual budget and quarterly budget for closed projects. Perhaps, the test/condition should be revised to consider that when 'actual end date' exists (activity date type = 4), then budget should no longer be expected. There are cases when 'actual end date' occur ahead of the 'planned end date'.

Thank you - we will amend the test to no longer include closed activities (removing status code 4).
