### ISSUE TITLE
Project budget document

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#11]
## Description

This is a specific budget detailing what the intended spending is for the different lines of the individual activity.

This can be either at the activity or transaction level, and is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the aid type is budget support (A01 or A02) or if the default aid type code is administrative costs (G01).

## Proposed test

```python
Budget document is present
    Given an IATI activity
     And the activity is current
     And `activity-status/@code` is one of 2, 3 or 4
     And `default-aid-type/@code` is not any of A01, A02 or G01
     And `transaction/aid-type/@code` is not any of A01 or A02
     Then `document-link/category[@code="A05"]` should be present
```

**Comment by ToonVB** [comment]
In addition to Types of Aid A01, A02 and G01 that are indicated above, this element is neither useful/meaningful for Types of Aid B02 (multilateral core contributions)  .

**Comment by publishwhatyoufund** [comment]
@ToonVB 

Thanks for you input here - we have done some surveying of data and found that some donors are including budget documents with their core contributions to multi-laterals.  

Since it is possible and more transparent to publish budgets for these activities we will not exclude aid type B02.
