### ISSUE TITLE
Budget alignment

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#14]
## Description

The budget alignment indicator helps to link the activity to the recipient country government’s own budget codes.

This is only expected if the activity is in the implementation, completion or post-completion phase, and if the aid type is not budget support. This is not expected if the aid type is budget support (A01 or A02) or if the default aid type code is administrative costs (G01).

The test follows the guidance on country budget alignment, found here on the IATI reference website: http://reference.iatistandard.org/203/activity-standard/overview/country-budget-alignment/

This guidance also includes the relevant CRS codelist guidance that will be used for this test.

## Proposed test

Firstly:
```python
   Capital spend is present
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02 or G01
    And `transaction/aid-type/@code` is not any of A01 or A02
    Then `capital-spend` should be present
```

Secondly:
```python
   Publish detailed CRS purpose codes in the sector field
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02 or G01
    And `transaction/aid-type/@code` is not any of A01 or A02
    Then `sector code` should be present
    And `sector code` should not be broad “multisector aid” or “sector not specified” purpose codes
    And `sector code` should be the more detailed “voluntary” CRS purpose codes, not “parent” codes
```

## Proposed change

This indicator was called "Capital spend" in the 2018 Index, and only tested whether the capital spend element was present in an activity.  The proposed change is to add the additional sector code tests that check whether sector codes being used will allow for alignment with country budgets.  This follows IATI guidance on the topic.

This is actually similar to the way the indicator worked in the 2016 Index when it was called "Budget identifier". However, the Budget Identifier codelist was deprecated which is why it was changed to "Capital spend" in 2018. The new budget alignment codelist will be based on the IATI guidance.

**Comment by markbrough** [comment]
This is an excellent and important update to the Index (NB as stated above, previous versions of the Index also included such an indicator, though in a different form).

Since the early days of IATI, it has been a key goal to make aid data available to partner country governments in a way that can be incorporated into their own decision-making processes. There are a number of other features of IATI data that make this easier (e.g. frequency, disbursements (#13), budgets (#10)). The work around what used to be called the "budget identifier" was the final outstanding piece of the standard, involving two components in its final incarnation:
* **more detailed sector codes**, which are much more in line with partner country classifications, making it possible to automatically map donor data against budget classifications (the country can then verify this data, rather than having to do all the coding from scratch)
* **a high-level breakdown by economic classification** (to identify recurrent versus capital expenditure) -- making it easier to identify where donors are undertaking investments that will likely have a future impact on the budget.

By encouraging organisations to gradually provide more detail in the way their projects are classified, this change would have broader benefits in addition to mapping to budgets. It should therefore lead to quite a big improvement in the quality and usefulness of data published by organisations taking part in the Aid Transparency Index.

**Comment by ToonVB** [comment]
In addition to Types of Aid A01, A02 and G01 that are indicated above, this element is neither useful/meaningful for Types of Aid B02 (multilateral core contributions) and E through H, nor (often occurring simultaneously) in case of Recipient code = 998 (Developing   countries, unspecified) .

**Comment by FMadsen** [comment]
The proposed change is in  the spirit of the IATI decision on the "Budget Identifier". However, I wonder how you will assess publishers' use of  the code list. Some issues: 1) the the DAC list extended with the voluntary codes is relatively new - would you apply the last line of the test to "old' activities? 2) In some cases the addition to the  new voluntary codes does not make the original xxxx0 codes obsolete, which makes the use of the criteria as formulated in the last line of the test a bit problematic. 3) The IATI guidance on the sector code list does not really help - there the "parent" and "voluntary" sector codes are listed without differentiation. Also, IATI guidance still carries some old budget identifier code lists.

**Comment by markbrough** [comment]
Hi @FMadsen -- I can't speak for @publishwhatyoufund but here are some thoughts on your questions:
1) The DAC list [was approved in February 2016](https://www.oecd.org/officialdocuments/publicdisplaydocumentpdf/?cote=DCD/DAC/STAT(2015)30/REV1&docLanguage=En), "for reporting on a voluntary basis as from 2016 reporting on 2015 activities". DAC members have been able to use these codes for their CRS reporting for the last four years. According to the test definition above, the Index would only test activities that meet [the current data test](https://github.com/pwyf/latest-index-indicator-definitions/issues/1), which essentially looks at activities with some activity in the last twelve months. This seems very reasonable to me?
2) The last line just means that the 15 broad purpose codes should not be used (implementing [section 2b of the guidance](http://reference.iatistandard.org/203/activity-standard/overview/country-budget-alignment/)). Instead, the more detailed voluntary purpose codes underneath them should be used. I pasted the 15 codes at the bottom of this comment.
3) Agreed, the IATI guidance / codelists could be clearer. @andylolz shared a very helpful and concise list of the various codes [here](https://discuss.iatistandard.org/t/mapping-budget-identifiers-and-dac-sectors/1322/4). I guess this a question for IATI?

**15 "parent" codes that should not be used**
(just copying/pasting from the [OECD DAC CRS codelists file](https://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/DAC-CRS-CODES.xls))

Code | Description
-- | --
11230 | Basic life   skills for youth and adults
11320 | Secondary education
15110 | Public sector policy   and administrative management
15111 | Public finance   management (PFM)
15112 | Decentralisation and   support to subnational government
15114 | Domestic revenue   mobilisation
15130 | Legal and judicial   development
16010 | Social Protection
16061 | Culture and   recreation
21010 | Transport policy and   administrative management
21020 | Road transport
22010 | Communications policy   and administrative management
23110 | Energy policy and   administrative management
43030 | Urban development and   management
43040 | Rural development

**Comment by rjboles** [comment]
We are assuming here that capital-spend can be accurately reported as 0% and be understood as present. Is this true?

**Comment by FMadsen** [comment]
Thank you, Mark – this is helpful.
Frank

**Comment by jzheng-79** [comment]
Similar question - capital-spend can be accurately reported as 0% and be understood as present, correct?

Agree that this is a great and important update to enable linking to recipient country government's budget codes.  We (UNICEF) already mapped our expenses to DAC codes in 2018. However, some of the broad sector codes have been used in our mapping. Excluding these codes now to meet ATI criteria will cause inconsistency in our financial reporting.
 
In additional, 'country budget alignment' is introduced in IATI schema 2.03, where UNICEF is current using 2.02.

We welcome the change/introducing this indicator, but request to remove the restriction on the broad sector codes.

**Comment by cmmarschner** [comment]
The test needs to be clearer when you reference: "And `sector code` should be the more detailed “voluntary” CRS purpose codes, not “parent” codes". I'm assuming this means that where voluntary codes exist, they should be used, but that is not what the test says. There are not voluntary codes available for all sectors, just some. Also looking at the DAC codes structure, I can't see how to automate a test to identify which detailed codes are 'valid' and which are not. There is nothing that differentiates the "15 broad purpose codes" from the other 5-digit DAC codes.

I don't disagree with the purpose of the test per se but don't think the test is described clearly enough and I think the structure of the DAC codes make this complicated to implement in systems.

**Comment by YohannaLoucheur** [comment]
Thanks PWYF team for revising this indicator in light of the recent guidance.
The test makes sense overall. However, I would support some of the comments/refinements suggested above: 
- per @toonvb "In addition to Types of Aid A01, A02 and G01 that are indicated above, this element is neither useful/meaningful for Types of Aid B02 (multilateral core contributions) and E through H,". I think that will be true in most cases. We'll have to rely on the receiving multilateral organisations to provide the detailed coding.

- @rjboles asked "We are assuming here that capital-spend can be accurately reported as 0% and be understood as present." Indeed, this is also our understanding (and practice) and we expect the test to work that way.
 
On the other hand, I would disagree with @toonvb's suggestion to exclude activities with a 998 recipient code (multiple countries). The data can still provide useful information for budget alignment even if several countries are potential recipients. 

thanks!

**Comment by publishwhatyoufund** [comment]
Thanks everyone for your input on this and to @markbrough for the detailed explanations.

@rjboles and @jzheng-79 
For capital spend you should report the percentage of project expenditure that is capital expenditure - this can be 0%.

@cmmarschner 
We will check to see if an activity is using a code on the CRS purpose codes codelist and not one of the 6 "broad" codes and 15 "parent" codes to determine whether an activity passes or fails this test.

@ToonVB
Since the specific sector codes can be used for core contributions and other aid types, we will not exclude these. 

@jzheng-79 
One of the reasons we are including this test is to encourage use of the codes that can be used to map against budgets. It's worth noting that this work was developed over many years by an IATI working group and then passed by WP-STAT about 3-4 years ago. If donors want to make their aid data useful to partner countries in their budget processes, they should not use very broad codes that make it hard to understand the nature of a particular project and therefore where it should be placed in the budget.
