### ISSUE TITLE
Procurement

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#15]
## Description

Tenders are the individual contracts or proposals that have been put out to invite bids from companies or organisations that want to provide goods and services for an activity.

Contracts are the individual contract(s) signed with a company, organisation or individual that provides goods and services for the activity.

These can be either at the activity or transaction level, and is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the aid type is budget support (A01 or A02) or if the default aid type code is administrative costs (G01).

## Proposed tests

Tender is present
```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02, B02 or G01
    And `transaction/aid-type/@code` is not any of A01, A02 or B02
    Then `document-link/category[@code="A10"]` should be present
```

Contract is present
```python  
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02, B02 or G01
    And `transaction/aid-type/@code` is not any of A01, A02 or B02
    Then `document-link/category[@code="A06"] | document-link/category[@code="A11"]` should be present
```

**Comment by ToonVB** [comment]
The idea that all publishing organisations only have aid-projects they implement themselves, involving the procurement of goods&services, is an oversimplification. 
Bilateral donors often don't do procurement themselves, which is done by the funded & implementing partner instead. 
In the case of BE, our bilateral non-governmental aid (often projects focusing on empowering the local civil society btw, i.e. without much procurement usually) as well as our bi-multi aid (implemented by multilaterals on the basis of earmarked funding) don't involve any procurement.

One could perhaps argue that where transaction type "Disbursement" is used, (meaning that funds are handed over to another organisation to set up activities) the implementing partner takes care of procurement, opposed to activities where the transaction type "Expenditures" is used , though I'm not sure all publishers do use this difference correctly  - and assuming of course that I myself do so :-)

**Comment by cmmarschner** [comment]
Agree with comment above - MCC does not contract its activities itself but rather grants them to other governments.

**Comment by ajoymccoy** [comment]
We agree with the comments above as well.  As a private foundation we are not performing implementation and procuring goods and services.  Well stated @ToonVB !
