### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#17]
## Description

The description of the activity is a descriptive text, longer than the title, explaining what the activity is.  The description must be at least 80 characters in length.

## Proposed test

Description is present
```python
   Given an IATI activity
    And the activity is current
    Then `description[text() or narrative/text()]` should be present
```

Description has at least 80 characters
```python
   Given an IATI activity
    And the activity is current
    Then `description/text() | description/narrative/text()` should have at least 80 characters
```

**Comment by MEdwards42** [comment]
The current application seems to indicate that descriptions must give information beyond that which is provided by the machine readable parts of the data. This seems counter to the principles of IATI that as much of the data as possible should all be machine readable. In practise, this has meant that h2 level descriptions, which we auto-generate are failing manual checks, where actually they are clear.

**Comment by publishwhatyoufund** [comment]
@MEdwards42 
As per the IATI [guidance](http://reference.iatistandard.org/201/activity-standard/iati-activities/iati-activity/description/) on descriptions, descriptions should be meaningful.  Descriptions auto-generated from the activity data do not provide additional information or a meaningful description of the activity. We will provide additional detail in the definition for the descriptions indicator in the re-issued 2020 Index Technical Paper.
