### ISSUE TITLE
Sub-national location

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#23]
## Description

The sub-national geographic location is information about where the activity is located within a country.

This is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the activity has been marked with the recipient region code 998 (bilateral/unspecified) - the intention is to exclude activities that do not have any geographic focus.

This is not expected if the default aid type code is administrative costs (G01).

## Proposed tests
Location (sub-national)
```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `recipient-region/@code` is not 998
    And `default-aid-type/@code` is not G01
    Then `location` should be present
``` 
Location (sub-national) coordinates or point
```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `recipient-region/@code` is not 998
    And `default-aid-type/@code` is not G01
    Then `location[coordinates or point]` should be present
```

**Comment by ToonVB** [comment]
This element should not be expected for activities with an Activity Scope of 1 through 4  either, "subnational location" only makes sense for activities with an Activity Scope > 4.

**Comment by rjboles** [comment]
We propose that aid categories 'A' and 'B' be excluded. In these cases, the reporting organization would not know the exact locations of the activities being that another organization oversees implementation and management.  Furthermore, there are still cases that would not have an associated sub-national location.  For example, many cases of technical assistance would not report locations.  It may be more realistic to score any organization reporting 80% to 90% of their activities with location data and fully compliant, or a full score. We would also like to point out IATI’s preliminary guidance on sub-national locations notes that location data should only be added when it is safe to do so. It is the publishing organisation’s responsibility to ensure that this is the case. The test should take this point about security into consideration.

**Comment by ajoymccoy** [comment]
As a private foundation we are not always determining the specific sub-national location or our projects are broader in the scope of geography served than a province/state/city and sometimes broader than a country or region (e.g. HIV R&D, Vaccines, etc.).  Thank you for considering.

**Comment by publishwhatyoufund** [comment]
@ToonVB 
Thank you for your input. We will continue to include these scopes in the test - multi-country or regional projects can also include specific sub-national locations where projects are being implemented.

@rjboles 
Thank you for your input. We will exclude aid types B01 and B02 from this test. Aid types under category A could include a sub-national location - contributions could be to municipal or regional government budgets, for example. Likewise with technical assistance - this could be given to a local government entity or involve advice about activity in a specific region or district.  We would not expect sub-national locations to be provided where this could pose a security risk. 

@ajoymccoy 
Thank you for your input.  At present we cannot identify a mechanism to exclude these types of activity from the test, unless they are of aid type B01, in which case they will now be excluded.
