### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#30]
## Description
The terms and conditions of the activity may also be referred to as benchmarks, priors, or involve words such as “subject to…”. They are specific to an individual activity and explain what the recipient must do in order to be eligible for the funds to be released.

This is only expected if the activity is in the implementation, completion or post-completion phase.

## Proposed test
Firstly:
```python
For each current activity,
i​f `activity-status/@code` i​s one of (2, 3, 4)
then `conditions` should be present
```
Secondly:
```python
i​f `activity-status/@code` i​s one of (2, 3, 4)
then `document-link/category[@code="A04"]` should be present
```

**Comment by rjboles** [comment]
USAID stands by our stance that USAID and many other organizations do not have activity specific conditions.  In the case of USAID, any deliverables that must be fulfilled by the implementing partner would be stated in a contract or cooperative agreement.  USAID does have standards that implementing partners must meet, but these are not activity specific and apply across any partner regardless of the activity.  We are happy to link to relevant chapters of the USAID Automated Directive System, but this has not been accepted in the past.

**Comment by jzheng-79** [comment]
UNICEF does not have 'activity' specific conditions. We sign a Programme Cooperation Agreement (PCA) with our civil society implementing partners, and it governs the CSO’s implementation of any programme activities agreed to with UNICEF in support of the achievement of the (5-year) Country Programme Document. It outlines general responsibilities of the parties, as well as reporting requirements.

**Comment by publishwhatyoufund** [comment]
@rjboles @jzheng-79 
The terms and conditions of the activity may also be referred to as benchmarks, priors, or involve words such as “subject to…”. They are specific to an individual activity and explain what the recipient must do in order to be eligible for the funds to be released. 

These conditions are often found in the contract or grant agreement associated with the project.

Standard terms and conditions templates are not accepted for this indicator.
