### ISSUE TITLE
Pre- and/or post-project impact appraisals

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#32]
## Description

Pre-project impact appraisals explain the totality of positive and negative, primary and secondary effects expected to be produced by a development intervention.

This is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the default aid type code is administrative costs (G01).

## Proposed test

```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of B02 or G01
    Then `document-link/category[@code="A01"]` should be present
```

**Comment by ToonVB** [comment]
As outlined already elsewhere, as regards bilateral donors, the notion that these are only, or even mainly,  "doing" projects is an oversimplification: as their aid flows range also from B02 (multilateral core contributions) over the other B types, D through H, they don't dispose of such clear-cut well-defined "project" documentation in a lot of cases. This applies to a number of the other indicators listed here as well of course. 
Perhaps a differentiated approach (or at the very least a separate league/ranking) for bilateral donors would be worthwile and fitting.

**Comment by rjboles** [comment]
Similar to our comments on evaluations and results, some USAID activities by default will never have impact appraisals to publish. We propose excluding A01, B02, and B04 aid types or something similar to hone the test’s measurement of transparency.

**Comment by jzheng-79** [comment]
UNICEF has already adopted results-based model for several years (as opposed to the project-approach). We do not have 'pre and/or post-project impact appraisal' per se.
In preparing the country programme, UNICEF develops the Theory of Change (ToC) for each output or sector, which identifies risks and potential impacts.

**Comment by publishwhatyoufund** [comment]
@ToonVB @rjboles 
Thank you for your input.  As well as G01, we will exclude aid types A, B and D through H from this test.

@jzheng-79 
Thank you for the input. Any document which includes an assesses of the totality of positive and negative primary and secondary impacts expected to be produced by a project will suffice to pass this test.  This could be part of a wider project planning or business case document.
