### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#34]
## Description
The results show whether activities achieved their intended outputs in accordance with the stated goals or plans.

This is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the default aid type code is administrative costs (G01).

## Proposed tests

Firstly (results data):
```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not G01
    Then `result` should be present
 ```
Secondly (results documents):
```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not G01
    Then `document-link/category[@code="A08"]` should be present
```

**Comment by ToonVB** [comment]
In case of Type of Aid B02 (multilateral core contributions) f.i. , most bilateral donors will not dispose of such results info, moreover, given that B02 flows are contributions to the regular budget of a multi, it's not feasible to provide comprehensive useful info, which is in any case taken up by the multilateral in question, through its website and annual report etc...

**Comment by rjboles** [comment]
Similar to our comments on evaluations and impact appraisals, some USAID activities by default will never have activity results to publish. We propose excluding A01, B02, and B04 aid types or something similar to hone the test’s measurement of transparency.

**Comment by publishwhatyoufund** [comment]
@ToonVB @rjboles 

Thanks for your input - we have done some surveying of data and found that some donors are including results with their core contributions to multilaterals, budget support and basket funds.

Since it is possible and more transparent to publish results for these activities we will not exclude aid types A01, B02 or B04.
