### ISSUE TITLE
Country Strategy or Memorandum of Understanding 

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#7]
## Description

A country strategy paper sets out the organisation’s planned approach and activities in the recipient country.

A Memorandum of Understanding (MoU) is a document which details the agreement usually between the organisation and recipient government for the provision of aid in the country.

Note: We will accept a country strategy paper (B03) or a country-level Memorandum of Understanding (B13). We’ll also accept A09 documents where applicable.

## Proposed test

```
the percentage of countries for which there are current activities, which have a country strategy paper or MoU
```

**Comment by rjboles** [comment]
USAID provides the most up-to-date country strategies available. Due to the strategy development cycle, a country strategy may expire or be extended until a new strategy is posted. We hope the test will assess that a country strategy is simply publicly available, as they are on the USAID website.

**Comment by publishwhatyoufund** [comment]
Since strategy documents should be forward looking, we would expect documents to be valid at the time we review them. This means an expired or out of date strategy document would not satisfy this test.  A strategy document that has been extended and is current at the time we review it would pass this test, however.
