### ISSUE TITLE
Total Organisation Budget

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#8]
## Description

The total organisation budget is the total amount that the organisation will be allocated by the government or its funders per year for the next three years.

## Proposed test

Points are awarded for providing a `total-budget` for each year forward, for the next three years.

## Example

If data collection ends on 2020-06-01, then the following would score full points:
``` python
<total-budget>
  <period-start iso-date="2020-01-01" />
  <period-end iso-date="2020-12-31" />
  <value currency="USD" value-date="2020-01-01">250000000</value>
</total-budget>
<total-budget>
  <period-start iso-date="2021-01-01" />
  <period-end iso-date="2021-12-31" />
  <value currency="USD" value-date="2021-01-01">300000000</value>
</total-budget>
<total-budget>
  <period-start iso-date="2022-01-01" />
  <period-end iso-date="2022-12-31" />
  <value currency="USD" value-date="2022-01-01">350000000</value>
</total-budget>
```

**Comment by MEdwards42** [comment]
We can only publish what has been decided upon.  If this is not available three years in advance, and is therefore not published via IATI then assessing against this is not a mark of a lack of transparency but rather, of the perceived quality of data.

**Comment by jzheng-79** [comment]
Similarly UNICEF publishes the organisation budgeted that has been decided upon in our Strategic Plan (integrated budget). Each SP runs for four years, and the budget review (for next SP) is not started until the 3rd year. So it does not seem to be rationale to force a three-year forward-looking period.
